language: php
php:
    - 5.5
    - 5.6
    - hhvm

install:
    - composer install

before_script:
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - phpcs --standard=PSR2 src --report=summary